/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Upload_MaterialsRouteImport } from './routes/upload_Materials'
import { Route as My_UploadsRouteImport } from './routes/my_Uploads'
import { Route as DiscussionRouteImport } from './routes/discussion'
import { Route as IndexRouteImport } from './routes/index'

const Upload_MaterialsRoute = Upload_MaterialsRouteImport.update({
  id: '/upload_Materials',
  path: '/upload_Materials',
  getParentRoute: () => rootRouteImport,
} as any)
const My_UploadsRoute = My_UploadsRouteImport.update({
  id: '/my_Uploads',
  path: '/my_Uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussionRoute = DiscussionRouteImport.update({
  id: '/discussion',
  path: '/discussion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discussion': typeof DiscussionRoute
  '/my_Uploads': typeof My_UploadsRoute
  '/upload_Materials': typeof Upload_MaterialsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discussion': typeof DiscussionRoute
  '/my_Uploads': typeof My_UploadsRoute
  '/upload_Materials': typeof Upload_MaterialsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discussion': typeof DiscussionRoute
  '/my_Uploads': typeof My_UploadsRoute
  '/upload_Materials': typeof Upload_MaterialsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/discussion' | '/my_Uploads' | '/upload_Materials'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/discussion' | '/my_Uploads' | '/upload_Materials'
  id: '__root__' | '/' | '/discussion' | '/my_Uploads' | '/upload_Materials'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscussionRoute: typeof DiscussionRoute
  My_UploadsRoute: typeof My_UploadsRoute
  Upload_MaterialsRoute: typeof Upload_MaterialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload_Materials': {
      id: '/upload_Materials'
      path: '/upload_Materials'
      fullPath: '/upload_Materials'
      preLoaderRoute: typeof Upload_MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my_Uploads': {
      id: '/my_Uploads'
      path: '/my_Uploads'
      fullPath: '/my_Uploads'
      preLoaderRoute: typeof My_UploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discussion': {
      id: '/discussion'
      path: '/discussion'
      fullPath: '/discussion'
      preLoaderRoute: typeof DiscussionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscussionRoute: DiscussionRoute,
  My_UploadsRoute: My_UploadsRoute,
  Upload_MaterialsRoute: Upload_MaterialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
